export { buildSceneMap, bakeAutoTiles, scatterGroundDecals, reachabilityCarve, makeRng, wallTagFor, furnishRoom, BUILDING_TEMPLATES, type RoomTemplate } from './cartographer.js';
export { buildCityScene, type CityRequest, type CityDistrictSpec } from './city.js';
export { LlmCityPlanner, normalizeDistricts, CITY_PLANNER_SYSTEM } from './city-planner.js';
export { runProgram, buildSpikeScene, GOLD_PROGRAMS, LlmSceneProgrammer, normalizeProgram, SCENE_PROGRAMMER_SYSTEM, type SceneProgram, type SceneOp } from './scene-program.js';
export { GENERATORS, ARCHETYPE_KINDS, type ArchetypeKind, type ArchetypeGenerator, type Contents, type GenContext } from './archetypes.js';
export { buildComponentSheet, COMPONENT_KINDS, type ComponentKind } from './component-lab.js';
export { checkStructure, type StructureReport } from './structure-check.js';
export { checkSemantics, BUILDING_SEMANTICS, type SemanticReport, type BuildingSemanticSpec } from './semantic-check.js';
export { THEMES, THEME_NAMES, themeNameFor, type Theme } from './themes.js';
export { type SceneComposer, FakeSceneComposer, LlmSceneComposer } from './composer.js';
export { loadAssetLibrary, type AssetLibrary, type AssetEntry, type AssetKind } from './asset-library.js';
export { renderSceneMapToPng } from './headless-render.js';
export { blockCottage, blockPlaza, blockTown } from './blocks.js';
export { buildCityMesh, cityMeshBlueprint, meshBlueprint, coreWall, type CityMesh, type CityBlueprint, type BlueprintPatch, type Patch, type Zone } from './citymesh.js';
export { buildCityBsp, cityBspBlueprint } from './citybsp.js';
export { realizeCityMesh, realizeCityBsp } from './city-realizer.js';
export { checkCoherence, type CoherenceReport } from './coherence-check.js';
export { CLAIM_APPROACH, CLAIM_CIRCULATION, CLAIM_STAGE, doorSideOf, type RealizedDoor } from './primitives.js';
export * from './catalog.js';
